const initialData = {
   tasks: [
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaaaa',
      name: 'GAS Interventions Project',
      expanded: true,
      startDate: '2025-01-01',
      endDate: '2025-12-31',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa01',
      name: 'Counters - Northern Region',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaaaa',
      expanded: true,
      startDate: '2025-01-05',
      endDate: '2025-06-30',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa02',
      name: 'Maintenance - Counter 1 (Tunis)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa01',
      duration: 2,
      percentDone: 30,
      startDate: '2025-01-10',
      endDate: '2025-01-12',
      requiredProfile: 'Technicien Maintenance',
      requiredCompetences: ['Inspection pipeline'],
      requiredFormations: ['Maintenance pipeline niveau 1'],
      requiredCertifications: ['Certificat Gaz Niveau 2'],
      businessUnit: 'Maintenance',
      priority: 'high',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa03',
      name: 'Coupure de gaz - Counter 2 (Bizerte)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa01',
      duration: 1,
      percentDone: 50,
      startDate: '2025-01-15',
      endDate: '2025-01-16',
      requiredProfile: 'Technicien Distribution',
      requiredCompetences: ['Pose de canalisation'],
      requiredFormations: ['Sécurité réseau gaz'],
      requiredCertifications: ['Certificat Gaz Niveau 1'],
      businessUnit: 'Distribution',
      priority: 'medium',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa04',
      name: 'Maintenance - Counter 3 (Ariana)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa01',
      duration: 3,
      percentDone: 70,
      startDate: '2025-02-01',
      endDate: '2025-02-04',
      requiredProfile: 'Technicienne Compteurs',
      requiredCompetences: ['Installation compteur'],
      requiredFormations: ['Formation compteurs intelligents'],
      requiredCertifications: ['Certificat installation compteur'],
      businessUnit: 'Metering',
      priority: 'low',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa05',
      name: 'Coupure de gaz - Counter 4 (Nabeul)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa01',
      duration: 2,
      percentDone: 20,
      startDate: '2025-02-10',
      endDate: '2025-02-12',
      requiredProfile: 'Contrôleuse Qualité',
      requiredCompetences: ['Audit sécurité'],
      requiredFormations: ['Audit ISO'],
      requiredCertifications: ['Certificat sécurité gaz'],
      businessUnit: 'Safety & Compliance',
      priority: 'medium',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa06',
      name: 'Maintenance - Counter 5 (Beja)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa01',
      duration: 2,
      percentDone: 60,
      startDate: '2025-02-20',
      endDate: '2025-02-22',
      requiredProfile: 'Chargé de support SCADA',
      requiredCompetences: ['Monitoring SCADA'],
      requiredFormations: ['Formation SCADA'],
      requiredCertifications: ['Certificat SCADA niveau 1'],
      businessUnit: 'Technical Support',
      priority: 'high',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa07',
      name: 'Coupure de gaz - Counter 6 (Jendouba)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa01',
      duration: 1,
      percentDone: 10,
      startDate: '2025-03-01',
      endDate: '2025-03-02',
      requiredProfile: 'Planificateur',
      requiredCompetences: ['Planification'],
      requiredFormations: ['Planning multi-équipe'],
      requiredCertifications: [],
      businessUnit: 'Operations',
      priority: 'low',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa08',
      name: 'Maintenance - Counter 7 (Zaghouan)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa01',
      duration: 2,
      percentDone: 80,
      startDate: '2025-03-10',
      endDate: '2025-03-12',
      requiredProfile: 'Technicienne sécurité',
      requiredCompetences: ['Inspection EPI'],
      requiredFormations: ['Formation sécurité gaz'],
      requiredCertifications: ['Certificat sécurité incendie'],
      businessUnit: 'Safety & Compliance',
      priority: 'high',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa09',
      name: 'Coupure de gaz - Counter 8 (Kef)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa01',
      duration: 2,
      percentDone: 30,
      startDate: '2025-03-20',
      endDate: '2025-03-22',
      requiredProfile: 'Technicien Maintenance',
      requiredCompetences: ['Réparation de fuites'],
      requiredFormations: ['Maintenance pipeline niveau 1'],
      requiredCertifications: ['Certificat Gaz Niveau 2'],
      businessUnit: 'Maintenance',
      priority: 'medium',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa0a',
      name: 'Maintenance - Counter 9 (Siliana)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa01',
      duration: 1,
      percentDone: 50,
      startDate: '2025-04-01',
      endDate: '2025-04-02',
      requiredProfile: 'Superviseure Maintenance',
      requiredCompetences: ['Planification'],
      requiredFormations: ['Formation gestion de crise'],
      requiredCertifications: ['Certificat Gaz Niveau 3'],
      businessUnit: 'Maintenance',
      priority: 'low',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa0b',
      name: 'Coupure de gaz - Counter 10 (Béja)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa01',
      duration: 3,
      percentDone: 90,
      startDate: '2025-04-10',
      endDate: '2025-04-13',
      requiredProfile: 'Technicienne Compteurs',
      requiredCompetences: ['Relevé de consommation'],
      requiredFormations: ['Formation compteurs intelligents'],
      requiredCertifications: ['Certificat installation compteur'],
      businessUnit: 'Metering',
      priority: 'high',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa0c',
      name: 'Pipelines - Eastern Region',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaaaa',
      expanded: true,
      startDate: '2025-07-01',
      endDate: '2025-12-15',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa0d',
      name: 'Maintenance - Pipeline A (Sfax)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa0c',
      duration: 4,
      percentDone: 40,
      startDate: '2025-07-05',
      endDate: '2025-07-09',
      requiredProfile: 'Technicien Réseau',
      requiredCompetences: ['Diagnostic terrain'],
      requiredFormations: ['Formation intervention rapide'],
      requiredCertifications: ['Certificat Gaz Niveau 2'],
      businessUnit: 'Operations',
      priority: 'high',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa0e',
      name: 'Coupure de gaz - Pipeline B (Gabès)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa0c',
      duration: 2,
      percentDone: 60,
      startDate: '2025-07-15',
      endDate: '2025-07-17',
      requiredProfile: 'Chargé de support SCADA',
      requiredCompetences: ['Alertes réseau'],
      requiredFormations: ['Formation GMAO'],
      requiredCertifications: ['Certificat SCADA niveau 1'],
      businessUnit: 'Technical Support',
      priority: 'medium',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa0f',
      name: 'Maintenance - Pipeline C (Tataouine)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa0c',
      duration: 3,
      percentDone: 25,
      startDate: '2025-08-01',
      endDate: '2025-08-04',
      requiredProfile: 'Superviseure Distribution',
      requiredCompetences: ['Optimisation pression'],
      requiredFormations: ['Leadership technique'],
      requiredCertifications: ['Certificat Gaz Niveau 3'],
      businessUnit: 'Distribution',
      priority: 'low',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa10',
      name: 'Coupure de gaz - Pipeline D (Medenine)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa0c',
      duration: 2,
      percentDone: 45,
      startDate: '2025-08-10',
      endDate: '2025-08-12',
      requiredProfile: 'Technicienne sécurité',
      requiredCompetences: ['Briefing sécurité'],
      requiredFormations: ['Formation sécurité gaz'],
      requiredCertifications: ['Certificat sécurité incendie'],
      businessUnit: 'Safety & Compliance',
      priority: 'medium',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa11',
      name: 'Maintenance - Pipeline E (Sousse)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa0c',
      duration: 2,
      percentDone: 75,
      startDate: '2025-08-20',
      endDate: '2025-08-22',
      requiredProfile: 'Technicien Maintenance',
      requiredCompetences: ['Inspection pipeline'],
      requiredFormations: ['Maintenance pipeline niveau 1'],
      requiredCertifications: ['Certificat Gaz Niveau 2'],
      businessUnit: 'Maintenance',
      priority: 'high',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa12',
      name: 'Coupure de gaz - Pipeline F (Monastir)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa0c',
      duration: 1,
      percentDone: 20,
      startDate: '2025-09-01',
      endDate: '2025-09-02',
      requiredProfile: 'Technicien Distribution',
      requiredCompetences: ['Pressurisation réseau'],
      requiredFormations: ['Sécurité réseau gaz'],
      requiredCertifications: ['Certificat Gaz Niveau 1'],
      businessUnit: 'Distribution',
      priority: 'low',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa13',
      name: 'Maintenance - Pipeline G (Mahdia)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa0c',
      duration: 3,
      percentDone: 50,
      startDate: '2025-09-10',
      endDate: '2025-09-13',
      requiredProfile: 'Technicienne Compteurs',
      requiredCompetences: ['Installation compteur'],
      requiredFormations: ['Formation compteurs intelligents'],
      requiredCertifications: ['Certificat installation compteur'],
      businessUnit: 'Metering',
      priority: 'medium',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa14',
      name: 'Coupure de gaz - Pipeline H (Kairouan)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa0c',
      duration: 1,
      percentDone: 10,
      startDate: '2025-09-20',
      endDate: '2025-09-21',
      requiredProfile: 'Technicien Réseau',
      requiredCompetences: ['Intervention urgente'],
      requiredFormations: ['Formation intervention rapide'],
      requiredCertifications: ['Certificat Gaz Niveau 2'],
      businessUnit: 'Operations',
      priority: 'high',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa15',
      name: 'Maintenance - Pipeline I (Zarzis)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa0c',
      duration: 2,
      percentDone: 90,
      startDate: '2025-10-01',
      endDate: '2025-10-03',
      requiredProfile: 'Contrôleuse Qualité',
      requiredCompetences: ['Inspection finale'],
      requiredFormations: ['Audit ISO'],
      requiredCertifications: ['Habilitation électrique B0'],
      businessUnit: 'Safety & Compliance',
      priority: 'high',
    },
    {
      _id: 'aaaaaaaaaaaaaaaaaaaaaa16',
      name: 'Coupure de gaz - Pipeline J (Nabeul)',
      parentId: 'aaaaaaaaaaaaaaaaaaaaaa0c',
      duration: 2,
      percentDone: 35,
      startDate: '2025-10-10',
      endDate: '2025-10-12',
      requiredProfile: 'Superviseure Maintenance',
      requiredCompetences: ['Gestion d équipe'],
      requiredFormations: ['Formation gestion de crise'],
      requiredCertifications: ['Certificat Gaz Niveau 3'],
      businessUnit: 'Maintenance',
      priority: 'medium',
    },
  ],
   dependencies: [
    { _id: 'bbbbbbbbbbbbbbbbbbbbbbbb', fromEvent: 'aaaaaaaaaaaaaaaaaaaaaa02', toEvent: 'aaaaaaaaaaaaaaaaaaaaaa03' },
    { _id: 'bbbbbbbbbbbbbbbbbbbbbbbb1', fromEvent: 'aaaaaaaaaaaaaaaaaaaaaa03', toEvent: 'aaaaaaaaaaaaaaaaaaaaaa04' },
    { _id: 'bbbbbbbbbbbbbbbbbbbbbbbb2', fromEvent: 'aaaaaaaaaaaaaaaaaaaaaa04', toEvent: 'aaaaaaaaaaaaaaaaaaaaaa05' },
    { _id: 'bbbbbbbbbbbbbbbbbbbbbbbb3', fromEvent: 'aaaaaaaaaaaaaaaaaaaaaa06', toEvent: 'aaaaaaaaaaaaaaaaaaaaaa07' },
    { _id: 'bbbbbbbbbbbbbbbbbbbbbbbb4', fromEvent: 'aaaaaaaaaaaaaaaaaaaaaa0d', toEvent: 'aaaaaaaaaaaaaaaaaaaaaa0e' },
    { _id: 'bbbbbbbbbbbbbbbbbbbbbbbb5', fromEvent: 'aaaaaaaaaaaaaaaaaaaaaa0e', toEvent: 'aaaaaaaaaaaaaaaaaaaaaa0f' },
    { _id: 'bbbbbbbbbbbbbbbbbbbbbbbb6', fromEvent: 'aaaaaaaaaaaaaaaaaaaaaa0f', toEvent: 'aaaaaaaaaaaaaaaaaaaaaa10' },
    { _id: 'bbbbbbbbbbbbbbbbbbbbbbbb7', fromEvent: 'aaaaaaaaaaaaaaaaaaaaaa11', toEvent: 'aaaaaaaaaaaaaaaaaaaaaa12' },
    { _id: 'bbbbbbbbbbbbbbbbbbbbbbbb8', fromEvent: 'aaaaaaaaaaaaaaaaaaaaaa12', toEvent: 'aaaaaaaaaaaaaaaaaaaaaa13' },
    { _id: 'bbbbbbbbbbbbbbbbbbbbbbbb9', fromEvent: 'aaaaaaaaaaaaaaaaaaaaaa13', toEvent: 'aaaaaaaaaaaaaaaaaaaaaa14' },
    { _id: 'bbbbbbbbbbbbbbbbbbbbbbbba', fromEvent: 'aaaaaaaaaaaaaaaaaaaaaa15', toEvent: 'aaaaaaaaaaaaaaaaaaaaaa16' },
  ],
  resources: [
    {
      _id: 'cccccccccccccccccccccccc',
      name: 'Sami Gharbi',
      initials: 'SG',
      profile: 'Technicien Maintenance',
      businessUnit: 'Maintenance',
      requiredCompetences: ['Inspection pipeline', 'Réparation de fuites'],
      requiredFormations: ['Maintenance pipeline niveau 1'],
      requiredCertifications: ['Certificat Gaz Niveau 2'],
      currentTasks: [
        'aaaaaaaaaaaaaaaaaaaaaa02',
        'aaaaaaaaaaaaaaaaaaaaaa09',
        'aaaaaaaaaaaaaaaaaaaaaa11'
      ]
    },
    {
      _id: 'cccccccccccccccccccccccd',
      name: 'Meriem Ben Salah',
      initials: 'MB',
      profile: 'Superviseure Maintenance',
      businessUnit: 'Maintenance',
      requiredCompetences: ['Planification', 'Gestion d’équipe'],
      requiredFormations: ['Formation gestion de crise'],
      requiredCertifications: ['Certificat Gaz Niveau 3'],
      currentTasks: [
      'aaaaaaaaaaaaaaaaaaaaaa02',
      'aaaaaaaaaaaaaaaaaaaaaa0a',
      'aaaaaaaaaaaaaaaaaaaaaa12',
      'aaaaaaaaaaaaaaaaaaaaaa16'
      ]
    },
    {
      _id: 'ccccccccccccccccccccccce',
      name: 'Ahmed Tlili',
      initials: 'AT',
      profile: 'Technicien Distribution',
      businessUnit: 'Distribution',
      requiredCompetences: ['Pose de canalisation', 'Pressurisation réseau'],
      requiredFormations: ['Sécurité réseau gaz'],
      requiredCertifications: ['Certificat Gaz Niveau 1'],
      currentTasks: [
        'aaaaaaaaaaaaaaaaaaaaaa03',
        'aaaaaaaaaaaaaaaaaaaaaa09',
        'aaaaaaaaaaaaaaaaaaaaaa12'
      ]
    },
    {
      _id: 'cccccccccccccccccccccccf',
      name: 'Nour Chikhaoui',
      initials: 'NC',
      profile: 'Technicienne Compteurs',
      businessUnit: 'Metering',
      requiredCompetences: ['Relevé de consommation', 'Installation compteur'],
      requiredFormations: ['Formation compteurs intelligents'],
      requiredCertifications: ['Certificat installation compteur'],
      currentTasks: [
        'aaaaaaaaaaaaaaaaaaaaaa04',
        'aaaaaaaaaaaaaaaaaaaaaa0b',
        'aaaaaaaaaaaaaaaaaaaaaa13'
      ]
    },
    {
      _id: 'ccccccccccccccccccccccd0',
      name: 'Rami Jaziri',
      initials: 'RJ',
      profile: 'Technicien Réseau',
      businessUnit: 'Operations',
      requiredCompetences: ['Diagnostic terrain', 'Intervention urgente'],
      requiredFormations: ['Formation intervention rapide'],
      requiredCertifications: ['SST', 'Certificat Gaz Niveau 2'],
      currentTasks: [
        'aaaaaaaaaaaaaaaaaaaaaa04',
        'aaaaaaaaaaaaaaaaaaaaaa0d',
        'aaaaaaaaaaaaaaaaaaaaaa14'
      ]
    },
    {
      _id: 'ccccccccccccccccccccccd1',
      name: 'Fatma Khemiri',
      initials: 'FK',
      profile: 'Contrôleuse Qualité',
      businessUnit: 'Safety & Compliance',
      requiredCompetences: ['Audit sécurité', 'Inspection finale'],
      requiredFormations: ['Sécurité incendie', 'Audit ISO'],
      requiredCertifications: ['Habilitation électrique B0', 'Certificat sécurité gaz'],
      currentTasks: [
        'aaaaaaaaaaaaaaaaaaaaaa05',
        'aaaaaaaaaaaaaaaaaaaaaa0d',
        'aaaaaaaaaaaaaaaaaaaaaa15'
      ]
    },
    {
      _id: 'ccccccccccccccccccccccd2',
      name: 'Mohamed Zghal',
      initials: 'MZ',
      profile: 'Chargé de support SCADA',
      businessUnit: 'Technical Support',
      requiredCompetences: ['Monitoring SCADA', 'Alertes réseau'],
      requiredFormations: ['Formation SCADA', 'Formation GMAO'],
      requiredCertifications: ['Certificat SCADA niveau 1'],
      currentTasks: [
        'aaaaaaaaaaaaaaaaaaaaaa06',
        'aaaaaaaaaaaaaaaaaaaaaa0e',
        'aaaaaaaaaaaaaaaaaaaaaa15'
      ]
    },
    {
      _id: 'ccccccccccccccccccccccd3',
      name: 'Amina Ferjani',
      initials: 'AF',
      profile: 'Superviseure Distribution',
      businessUnit: 'Distribution',
      requiredCompetences: ['Supervision réseau', 'Optimisation pression'],
      requiredFormations: ['Leadership technique'],
      requiredCertifications: ['Certificat Gaz Niveau 3'],
      currentTasks: [
        'aaaaaaaaaaaaaaaaaaaaaa06',
        'aaaaaaaaaaaaaaaaaaaaaa0f'
      ]
    },
    {
      _id: 'ccccccccccccccccccccccd4',
      name: 'Tarek Mahfoudh',
      initials: 'TM',
      profile: 'Planificateur',
      businessUnit: 'Operations',
      requiredCompetences: ['Planification', 'Gestion du planning'],
      requiredFormations: ['Excel avancé', 'Planning multi-équipe'],
      requiredCertifications: [],
      currentTasks: [
        'aaaaaaaaaaaaaaaaaaaaaa07',
        'aaaaaaaaaaaaaaaaaaaaaa0f'
      ]
    },
    {
      _id: 'ccccccccccccccccccccccd5',
      name: 'Salma Baccar',
      initials: 'SB',
      profile: 'Technicienne sécurité',
      businessUnit: 'Safety & Compliance',
      requiredCompetences: ['Inspection EPI', 'Briefing sécurité'],
      requiredFormations: ['Formation sécurité gaz'],
      requiredCertifications: ['Certificat sécurité incendie'],
      currentTasks: [
        'aaaaaaaaaaaaaaaaaaaaaa08',
        'aaaaaaaaaaaaaaaaaaaaaa10'
      ]
    }
  ],

  assignments: [
    { _id: 'dddddddddddddddddddddddd', event: 'aaaaaaaaaaaaaaaaaaaaaa02', resource: 'cccccccccccccccccccccccc', units: 70 },
    { _id: 'ddddddddddddddddddddddde', event: 'aaaaaaaaaaaaaaaaaaaaaa02', resource: 'cccccccccccccccccccccccd', units: 30 },
    { _id: 'dddddddddddddddddddddddf', event: 'aaaaaaaaaaaaaaaaaaaaaa03', resource: 'ccccccccccccccccccccccce', units: 100 },
    { _id: 'dddddddddddddddddddddde0', event: 'aaaaaaaaaaaaaaaaaaaaaa04', resource: 'cccccccccccccccccccccccf', units: 50 },
    { _id: 'dddddddddddddddddddddde1', event: 'aaaaaaaaaaaaaaaaaaaaaa04', resource: 'ccccccccccccccccccccccd0', units: 50 },
    { _id: 'dddddddddddddddddddddde2', event: 'aaaaaaaaaaaaaaaaaaaaaa05', resource: 'ccccccccccccccccccccccd1', units: 100 },
    { _id: 'dddddddddddddddddddddde3', event: 'aaaaaaaaaaaaaaaaaaaaaa06', resource: 'ccccccccccccccccccccccd2', units: 60 },
    { _id: 'dddddddddddddddddddddde4', event: 'aaaaaaaaaaaaaaaaaaaaaa06', resource: 'ccccccccccccccccccccccd3', units: 40 },
    { _id: 'dddddddddddddddddddddde5', event: 'aaaaaaaaaaaaaaaaaaaaaa07', resource: 'ccccccccccccccccccccccd4', units: 100 },
    { _id: 'dddddddddddddddddddddde6', event: 'aaaaaaaaaaaaaaaaaaaaaa08', resource: 'ccccccccccccccccccccccd5', units: 100 },
    { _id: 'dddddddddddddddddddddde7', event: 'aaaaaaaaaaaaaaaaaaaaaa09', resource: 'cccccccccccccccccccccccc', units: 50 },
    { _id: 'dddddddddddddddddddddde8', event: 'aaaaaaaaaaaaaaaaaaaaaa09', resource: 'ccccccccccccccccccccccce', units: 50 },
    { _id: 'dddddddddddddddddddddde9', event: 'aaaaaaaaaaaaaaaaaaaaaa0a', resource: 'cccccccccccccccccccccccd', units: 100 },
    { _id: 'ddddddddddddddddddddddea', event: 'aaaaaaaaaaaaaaaaaaaaaa0b', resource: 'cccccccccccccccccccccccf', units: 100 },
    { _id: 'ddddddddddddddddddddddeb', event: 'aaaaaaaaaaaaaaaaaaaaaa0d', resource: 'ccccccccccccccccccccccd0', units: 70 },
    { _id: 'ddddddddddddddddddddddec', event: 'aaaaaaaaaaaaaaaaaaaaaa0d', resource: 'ccccccccccccccccccccccd1', units: 30 },
    { _id: 'dddddddddddddddddddddded', event: 'aaaaaaaaaaaaaaaaaaaaaa0e', resource: 'ccccccccccccccccccccccd2', units: 100 },
    { _id: 'ddddddddddddddddddddddee', event: 'aaaaaaaaaaaaaaaaaaaaaa0f', resource: 'ccccccccccccccccccccccd3', units: 50 },
    { _id: 'ddddddddddddddddddddddef', event: 'aaaaaaaaaaaaaaaaaaaaaa0f', resource: 'ccccccccccccccccccccccd4', units: 50 },
    { _id: 'ddddddddddddddddddddddf0', event: 'aaaaaaaaaaaaaaaaaaaaaa10', resource: 'ccccccccccccccccccccccd5', units: 100 },
    { _id: 'ddddddddddddddddddddddf1', event: 'aaaaaaaaaaaaaaaaaaaaaa11', resource: 'cccccccccccccccccccccccc', units: 100 },
    { _id: 'ddddddddddddddddddddddf2', event: 'aaaaaaaaaaaaaaaaaaaaaa12', resource: 'cccccccccccccccccccccccd', units: 50 },
    { _id: 'ddddddddddddddddddddddf3', event: 'aaaaaaaaaaaaaaaaaaaaaa12', resource: 'ccccccccccccccccccccccce', units: 50 },
    { _id: 'ddddddddddddddddddddddf4', event: 'aaaaaaaaaaaaaaaaaaaaaa13', resource: 'cccccccccccccccccccccccf', units: 100 },
    { _id: 'ddddddddddddddddddddddf5', event: 'aaaaaaaaaaaaaaaaaaaaaa14', resource: 'ccccccccccccccccccccccd0', units: 100 },
    { _id: 'ddddddddddddddddddddddf6', event: 'aaaaaaaaaaaaaaaaaaaaaa15', resource: 'ccccccccccccccccccccccd1', units: 50 },
    { _id: 'ddddddddddddddddddddddf7', event: 'aaaaaaaaaaaaaaaaaaaaaa15', resource: 'ccccccccccccccccccccccd2', units: 50 },
    { _id: 'ddddddddddddddddddddddf8', event: 'aaaaaaaaaaaaaaaaaaaaaa16', resource: 'cccccccccccccccccccccccd', units: 100 },
  ],
};

export { initialData };
